"""
AppCUI API reference (Sphinx extension).

When the build starts (``builder-inited``) this extension:

1. runs Doxygen on the public header (``docs/Doxyfile`` -> ``docs/build/doxygen/xml``);
2. generates reStructuredText pages in ``source/api`` from the Doxygen XML: an index, one page per namespace
   (description, nested namespaces, classes, enumerations, type aliases, variables and functions) and one page per
   class / struct declared directly in a namespace (nested types are documented on the page of their parent).

The pages only contain Breathe directives - Breathe renders the declarations from the same XML. Generated files are
rewritten only when their content changes (incremental Sphinx builds stay fast) and stale ones are removed, so the
output is a pure function of the header: the same header always produces the same pages.

Configuration (conf.py):
    appcui_doxyfile         path of the Doxyfile (its directory is the working directory of Doxygen)
    appcui_header           the public header (Doxygen parses a copy of it, see run_doxygen)
    appcui_doxygen          Doxygen executable (default: $DOXYGEN or "doxygen")
    appcui_api_output       folder (relative to the Sphinx source folder) that receives the generated pages
    appcui_api_namespaces   order of the namespaces in the index (others are appended alphabetically)
Set the environment variable APPCUI_DOCS_SKIP_API=1 to build the guides without Doxygen (the API reference is then
replaced by a placeholder page).
"""

import os
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

from sphinx.errors import ExtensionError
from sphinx.util import logging

logger = logging.getLogger(__name__)

GENERATED_MARKER = ".. generated by _ext/appcui_api.py - do not edit (regenerated by every build)\n"


# --------------------------------------------------------------------------------------------- doxygen
def doxyfile_settings(doxyfile):
    """single-valued 'TAG = value' settings of a Doxyfile"""
    settings = {}
    for line in doxyfile.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\s*([A-Z_]+)\s*=\s*([^\\#]*?)\s*$", line)
        if m:
            settings[m.group(1)] = m.group(2).strip('"')
    return settings


def run_doxygen(app):
    doxyfile = Path(app.config.appcui_doxyfile).resolve()
    if not doxyfile.is_file():
        raise ExtensionError(f"appcui_api: Doxyfile not found: {doxyfile}")
    doxygen = app.config.appcui_doxygen or os.environ.get("DOXYGEN") or "doxygen"
    if shutil.which(doxygen) is None and not Path(doxygen).is_file():
        raise ExtensionError(
            "appcui_api: Doxygen was not found (needed for the API reference).\n"
            "  Install it (https://www.doxygen.nl/download.html - Windows: winget install DoxygenProject.Doxygen, "
            "Ubuntu: apt install doxygen, macOS: brew install doxygen) or point the DOXYGEN environment variable to it.\n"
            "  To build only the guides, set APPCUI_DOCS_SKIP_API=1.")
    # Doxygen does not create intermediate folders: create the output folder it was configured with
    settings = doxyfile_settings(doxyfile)
    output_dir = doxyfile.parent / settings.get("OUTPUT_DIRECTORY", "")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Doxygen reads a copy of the header in which `friend X;` (C++11 form, not understood by Doxygen) is written
    # `friend class X;` - the same declaration, hidden by HIDE_FRIEND_COMPOUNDS. Line numbers are unchanged.
    header = Path(app.config.appcui_header).resolve()
    source_copy = output_dir / "input" / header.name
    source_copy.parent.mkdir(parents=True, exist_ok=True)
    text = header.read_text(encoding="utf-8")
    text = re.sub(r"^(\s*)friend\s+(?!class\b|struct\b|union\b|enum\b)([A-Za-z_][\w:]*)\s*;", r"\1friend class \2;",
                  text, flags=re.M)
    if not source_copy.is_file() or source_copy.read_text(encoding="utf-8") != text:
        source_copy.write_text(text, encoding="utf-8", newline="\n")
    extra_inputs = " ".join(f'"{p.relative_to(doxyfile.parent).as_posix()}"' for p in sorted(doxyfile.parent.glob("doxygen/*.dox")))
    config = doxyfile.read_text(encoding="utf-8")
    config += f'\nINPUT = "{source_copy.relative_to(doxyfile.parent).as_posix()}" {extra_inputs}\n'

    # "doxygen -" reads the configuration from stdin (the Doxyfile + the INPUT override)
    result = subprocess.run([doxygen, "-"], cwd=doxyfile.parent, input=config, capture_output=True, text=True)
    copy_path = source_copy.as_posix()
    for line in (result.stdout + result.stderr).splitlines():
        line = line.strip().replace(copy_path, header.as_posix())
        if line:
            logger.warning("doxygen: %s", line, type="appcui", subtype="doxygen")
    if result.returncode != 0:
        raise ExtensionError(f"appcui_api: Doxygen failed with exit code {result.returncode}")
    xml_dir = output_dir / settings.get("XML_OUTPUT", "xml")
    if not (xml_dir / "index.xml").is_file():
        raise ExtensionError(f"appcui_api: Doxygen did not produce {xml_dir / 'index.xml'}")
    return xml_dir


# --------------------------------------------------------------------------------------------- XML model
def text_of(element):
    """plain text of a Doxygen description element (brief / detailed)"""
    if element is None:
        return ""
    return re.sub(r"\s+", " ", "".join(element.itertext())).strip()


class Model:
    """the subset of the Doxygen XML needed to lay the pages out"""

    def __init__(self, xml_dir):
        self.xml_dir = xml_dir
        self.namespaces = {}  # name -> dict
        self.classes = {}  # name -> dict
        index = ET.parse(xml_dir / "index.xml").getroot()
        for compound in index.findall("compound"):
            kind, name, refid = compound.get("kind"), compound.findtext("name"), compound.get("refid")
            # only the AppCUI API (BUILTIN_STL_SUPPORT also creates a "std" namespace)
            if name != "AppCUI" and not name.startswith("AppCUI::"):
                continue
            # `using std::vector;` (AppCUI::StdIncludes) is seen as a class: these are the standard types
            if kind != "namespace" and name.startswith("AppCUI::StdIncludes::"):
                continue
            if kind == "namespace":
                self.namespaces[name] = self._load_namespace(refid, name)
            elif kind in ("class", "struct", "union"):
                self.classes[name] = self._load_class(refid, name, kind)
        # a class is documented on its own page only when its parent is a namespace (not another class)
        for c in self.classes.values():
            c["standalone"] = c["parent"] in self.namespaces or c["parent"] == ""

    def _compound(self, refid):
        return ET.parse(self.xml_dir / f"{refid}.xml").getroot().find("compounddef")

    def _load_namespace(self, refid, name):
        cd = self._compound(refid)
        ns = {
            "name": name,
            "brief": text_of(cd.find("briefdescription")),
            "namespaces": sorted(e.text for e in cd.findall("innernamespace")),
            "classes": sorted(e.text for e in cd.findall("innerclass")),
            "members": {"enum": [], "typedef": [], "variable": [], "function": []},
        }
        for section in cd.findall("sectiondef"):
            for m in section.findall("memberdef"):
                kind = m.get("kind")
                if kind not in ns["members"]:
                    continue
                member = {
                    "name": m.findtext("name"),
                    "params": [re.sub(r"\s+", " ", "".join(p.find("type").itertext())).strip()
                               for p in m.findall("param") if p.find("type") is not None],
                    "argsstring": m.findtext("argsstring") or "",
                }
                ns["members"][kind].append(member)
        return ns

    def _load_class(self, refid, name, kind):
        cd = self._compound(refid)
        parent = name.rsplit("::", 1)[0] if "::" in name else ""
        # template specializations ("A::B< int >") belong to the scope before the '<'
        if "<" in name:
            parent = name.split("<", 1)[0].rsplit("::", 1)[0]

        # Members whose type is an anonymous struct / union (`struct { ... } Menu;`, `union { ... };`) can not be
        # rendered by Breathe (Sphinx rejects their "[struct]" placeholder scope): they are left out of the member
        # list and shown as an excerpt of the header instead.
        # Function pointer fields (`T (*name)()`) are rendered the same way: Breathe can not rebuild their declarator.
        members, anonymous, excerpts = [], False, []
        for m in cd.iter("memberdef"):
            mname = m.findtext("name") or ""
            mtype = "".join(m.find("type").itertext()) if m.find("type") is not None else ""
            if m.get("kind") == "variable" and (mname.startswith("@") or "::@" in mtype or mtype.startswith("@")):
                anonymous = True
            elif m.get("kind") == "variable" and "(*" in mtype:
                anonymous = True
                loc = m.find("location")
                excerpts.append((loc.get("file"), int(loc.get("line")), int(loc.get("line"))))
            elif mname and mname not in members:
                members.append(mname)
        if anonymous:
            seen = set(excerpts)
            for ic in cd.findall("innerclass"):
                if "[" not in ic.text and "@" not in ic.text:
                    if ic.text.rsplit("::", 1)[-1] not in members:
                        members.append(ic.text.rsplit("::", 1)[-1])
                    continue
                loc = self._compound(ic.get("refid")).find("location")
                span = (loc.get("file"), int(loc.get("line")), int(loc.get("bodyend", loc.get("line"))))
                if span not in seen:
                    seen.add(span)
                    excerpts.append(span)
        return {
            "name": name,
            "kind": kind,
            "parent": parent,
            "brief": text_of(cd.find("briefdescription")),
            "members": members if anonymous else None,  # None = every member
            "excerpts": sorted(excerpts, key=lambda s: s[1]),
        }


# --------------------------------------------------------------------------------------------- pages
def slug(name):
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")


def role_text(title):
    """text of a :doc: link (a '<' would start the link target)"""
    return title.replace("\\", "\\\\").replace("<", "\\<").replace("`", "\\`")


def heading(title, char):
    return f"{title}\n{char * len(title)}\n"


def short_name(name):
    return name.split("<", 1)[0].rsplit("::", 1)[-1] + ("<" + name.split("<", 1)[1] if "<" in name else "")


def source_excerpt(span, cache):
    """lines [first, last] (1-based) of a source file, dedented"""
    path, first, last = span
    if path not in cache:
        cache[path] = Path(path).read_text(encoding="utf-8").splitlines()
    lines = cache[path][first - 1:last]
    indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
    return [l[indent:].rstrip() for l in lines]


def class_page(c, sources):
    title = short_name(c["name"])
    lines = [GENERATED_MARKER, "\n", heading(title, "="), "\n"]
    lines.append(f"``{c['name']}`` ({c['kind']})\n\n")
    lines.append(f".. doxygen{'struct' if c['kind'] == 'struct' else 'class' if c['kind'] == 'class' else 'union'}:: {c['name']}\n")
    if c["kind"] != "union":
        if c["members"] is None:
            lines.append("   :members:\n")
        elif c["members"]:
            lines.append(f"   :members: {', '.join(c['members'])}\n")
        lines.append("   :protected-members:\n   :undoc-members:\n")
    if c["excerpts"]:
        lines.append("\n" + heading("Other fields", "-") + "\n")
        lines.append("Declared in the header as:\n\n.. code-block:: c++\n\n")
        for i, span in enumerate(c["excerpts"]):
            if i:
                lines.append("\n")
            for l in source_excerpt(span, sources):
                lines.append(f"   {l}\n" if l else "\n")
    return "".join(lines)


def function_target(ns_name, member, overloaded):
    if not overloaded:
        return f"{ns_name}::{member['name']}"
    return f"{ns_name}::{member['name']}({', '.join(member['params'])})"


def namespace_page(model, ns, class_files):
    name = ns["name"]
    lines = [GENERATED_MARKER, "\n", heading(name, "="), "\n"]
    lines.append(f".. doxygennamespace:: {name}\n   :desc-only:\n\n")

    nested = [n for n in ns["namespaces"] if n in model.namespaces]
    if nested:
        lines.append(heading("Namespaces", "-") + "\n")
        for n in nested:
            brief = model.namespaces[n]["brief"]
            lines.append(f"* :doc:`{role_text(n)} <namespace_{slug(n)}>`" + (f" - {brief}" if brief else "") + "\n")
        lines.append("\n")

    classes = [c for c in ns["classes"] if c in model.classes and model.classes[c]["standalone"]]
    if classes:
        lines.append(heading("Classes", "-") + "\n")
        for c in classes:
            brief = model.classes[c]["brief"]
            lines.append(f"* :doc:`{role_text(short_name(c))} <{class_files[c]}>`" + (f" - {brief}" if brief else "") + "\n")
        lines.append("\n.. toctree::\n   :hidden:\n\n")
        for c in classes:
            lines.append(f"   {class_files[c]}\n")
        lines.append("\n")

    members = ns["members"]
    for kind, title, directive in (("enum", "Enumerations", "doxygenenum"),
                                   ("typedef", "Type aliases", "doxygentypedef"),
                                   ("variable", "Variables", "doxygenvariable")):
        if members[kind]:
            lines.append(heading(title, "-") + "\n")
            seen = set()
            for m in members[kind]:
                if m["name"] in seen:
                    continue
                seen.add(m["name"])
                lines.append(f".. {directive}:: {name}::{m['name']}\n\n")

    if members["function"]:
        lines.append(heading("Functions", "-") + "\n")
        counts = {}
        for m in members["function"]:
            counts[m["name"]] = counts.get(m["name"], 0) + 1
        emitted = set()
        for m in members["function"]:
            target = function_target(name, m, counts[m["name"]] > 1)
            if target in emitted:
                continue
            emitted.add(target)
            lines.append(f".. doxygenfunction:: {target}\n\n")
    return "".join(lines)


def index_page(model, order, ns_files):
    lines = [GENERATED_MARKER, "\n", heading("API reference", "="), "\n"]
    lines.append(
        "Generated from the public header ``AppCUI/include/AppCUI.hpp`` (the only header an application includes).\n"
        "Every declaration is listed, documented or not; descriptions come from the ``///`` comments of the header\n"
        "and from ``docs/doxygen/namespaces.dox``.\n\n")
    lines.append(".. code-block:: c++\n\n   #include <AppCUI.hpp>\n\n   using namespace AppCUI;\n\n")
    lines.append(heading("Namespaces", "-") + "\n")
    for n in order:
        brief = model.namespaces[n]["brief"]
        lines.append(f"* :doc:`{role_text(n)} <{ns_files[n]}>`" + (f" - {brief}" if brief else "") + "\n")
    lines.append("\n.. toctree::\n   :hidden:\n   :maxdepth: 2\n\n")
    for n in order:
        lines.append(f"   {ns_files[n]}\n")
    return "".join(lines)


def write_if_changed(path, content, written):
    written.add(path.resolve())
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def generate(app, xml_dir):
    out = Path(app.srcdir) / app.config.appcui_api_output
    out.mkdir(parents=True, exist_ok=True)
    model = Model(xml_dir)

    order = [n for n in app.config.appcui_api_namespaces if n in model.namespaces]
    order += sorted(n for n in model.namespaces if n not in order)
    ns_files = {n: f"namespace_{slug(n)}" for n in model.namespaces}
    class_files = {c: f"class_{slug(c)}" for c in model.classes}

    written = set()
    sources = {}
    write_if_changed(out / "index.rst", index_page(model, order, ns_files), written)
    for n in order:
        write_if_changed(out / f"{ns_files[n]}.rst", namespace_page(model, model.namespaces[n], class_files), written)
    for c, data in model.classes.items():
        if data["standalone"]:
            write_if_changed(out / f"{class_files[c]}.rst", class_page(data, sources), written)
    # remove pages of declarations that no longer exist
    for f in out.glob("*.rst"):
        if f.resolve() not in written and f.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            f.unlink()
    logger.info("appcui_api: %d namespaces, %d classes", len(model.namespaces),
                sum(1 for c in model.classes.values() if c["standalone"]))


def generate_placeholder(app):
    out = Path(app.srcdir) / app.config.appcui_api_output
    out.mkdir(parents=True, exist_ok=True)
    for f in out.glob("*.rst"):
        if f.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            f.unlink()
    content = (GENERATED_MARKER + "\n" + heading("API reference", "=") + "\n"
               "The API reference was not generated (``APPCUI_DOCS_SKIP_API`` is set). Install Doxygen and build the\n"
               "documentation again to generate it.\n")
    write_if_changed(out / "index.rst", content, set())


def on_builder_inited(app):
    if os.environ.get("APPCUI_DOCS_SKIP_API", "") not in ("", "0"):
        logger.warning("appcui_api: APPCUI_DOCS_SKIP_API is set - the API reference is not generated",
                       type="appcui", subtype="skip")
        generate_placeholder(app)
        return
    generate(app, run_doxygen(app))


def setup(app):
    app.add_config_value("appcui_doxyfile", "", "env")
    app.add_config_value("appcui_header", "", "env")
    app.add_config_value("appcui_doxygen", "", "env")
    app.add_config_value("appcui_api_output", "api", "env")
    app.add_config_value("appcui_api_namespaces", [], "env")
    app.connect("builder-inited", on_builder_inited)
    return {"version": "1.0", "parallel_read_safe": True, "parallel_write_safe": True}
