name: Version Increase

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      versionToUpdate:
        description: 'Version to update'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  version-ubuntu:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get Version to ENV and increase it
      run: |
        output=$(python .github/workflows/get_version_and_update.py AppCUI/include/AppCUI.hpp ${{ github.event.inputs.versionToUpdate }})
        echo "APPCUI_VERSION=$output" >> $GITHUB_ENV
      
    - name: Show Version
      run: echo "${{ env.APPCUI_VERSION }}"

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Updated AppCUI version ${{ env.APPCUI_VERSION }}" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
